name: Neox
options:
  bundleIdPrefix: com.neox
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  defaultConfig: Debug

targets:
  NeoxApp:
    type: application
    platform: iOS
    sources:
      - Neox
    entitlements:
      path: Neox/Neox.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.neox.app
        PRODUCT_NAME: Neox
        PRODUCT_MODULE_NAME: NeoxApp
        INFOPLIST_FILE: Neox/Info.plist
        CODE_SIGN_ENTITLEMENTS: Neox/Neox.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "6.0"
        TARGETED_DEVICE_FAMILY: "1"
        DEVELOPMENT_TEAM: "JABNLDLN8G"

  NeoxTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - NeoxTests
    dependencies:
      - target: NeoxApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.neox.app.tests
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/Neox.app/Neox
        BUNDLE_LOADER: $(TEST_HOST)

schemes:
  NeoxApp:
    build:
      targets:
        NeoxApp: all
    run:
      config: Debug
    test:
      targets:
        - NeoxTests
    archive:
      config: Release
